#!/bin/sh

mr_reboot() {

    #echo "mr_reboot"
    sudo rmmod x86-64-cameo-esc600-128q
    sudo i2cset -y 0 0x30 0xa1 0  

}

if [ $# -eq 0 ] || [ $@ = "-p" ] || [ $@ = "--reboot" ] || [ $@ = "--poweroff" ] || [ $@ = "-f" ] || [ $@ = "--force" ];  then
    mr_reboot
elif [ $@ = "--halt" ]; then
    #echo "halt" 
    sudo halt
else
    echo "unsupported option"
fi

